version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_backend101
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: backend101
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend101.sql:/docker-entrypoint-initdb.d/backend101.sql
    restart: always

volumes:
  pgdata:
